Me: Fixing errors from missing icon
Error: Could not load icon 'icon16.png' specified in 'action'.
Could not load manifest.

Prompt to update chatGPT: "Ok, there was an error because you specified an icon file in the manifest.json that I did not have. I have fixed it by adding a file called icon.png and changing all of the icon filenames in manifest.json to icon.png. I will continue testing now."